#pragma once

/* Drive ports */
#define RIGHT_FRONT_PORT 1
#define RIGHT_BACK_PORT 2
#define LEFT_FRONT_PORT 3
#define LEFT_BACK_PORT 4

/* Intake Ports */
#define INTAKE_PORT 5

/* Conveyor ports */
#define CONVEYOR_PORT 6

/* Launcher */
#define RIGHT_FEED 7
#define LEFT_FEED 8
#define RIGHT_LAUNCHER 9
#define LEFT_LAUNCHER 10

/* Climber */
#define RIGHT_CLIMBER_PORT 11
#define LEFT_CLIMBER_PORT 12

/* Solenoids */
#define COMPRESSOR_PCM 2
#define RIGHT_DRIVE_SHIFTER_PCM 2
#define LEFT_DRIVE_SHIFTER_PCM 2
#define CLIMBER_PCM 2
#define RIGHT_DRIVE_SHIFTER_LOW_GEAR_PORT 6
#define RIGHT_DRIVE_SHIFTER_HIGH_GEAR_PORT 7
#define LEFT_DRIVE_SHIFTER_LOW_GEAR_PORT 0
#define LEFT_DRIVE_SHIFTER_HIGH_GEAR_PORT 1

/* Climber Solenoids */
#define RIGHT_CLIMBER_LOW_PORT 2
#define RIGHT_CLIMBER_HIGH_PORT 3
#define LEFT_CLIMBER_LOW_PORT 4
#define LEFT_CLIMBER_HIGH_PORT 5
#define INTAKE_SOLENOID_IN_PORT 12
#define INTAKE_SOLENOID_OUT_PORT 13