#pragma once

/* Drive ports */
#define RIGHT_FRONT_PORT 1
#define RIGHT_BACK_PORT 2
#define LEFT_FRONT_PORT 3
#define LEFT_BACK_PORT 4

/* Intake Ports */
#define INTAKE_PORT 5

/* Conveyor ports */
#define CONVEYOR_PORT 6

/* Solenoids */
#define COMPRESSOR_PCM 2
#define RIGHT_DRIVE_SHIFTER_PCM 2
#define LEFT_DRIVE_SHIFTER_PCM 2
#define RIGHT_DRIVE_SHIFTER_LOW_GEAR_PORT 6
#define RIGHT_DRIVE_SHIFTER_HIGH_GEAR_PORT 7
#define LEFT_DRIVE_SHIFTER_LOW_GEAR_PORT 0
#define LEFT_DRIVE_SHIFTER_HIGH_GEAR_PORT 1


